export const STAFF_SALARY_REQUEST = "STAFF_SALARY_REQUEST";
export const STAFF_SALARY_SUCCESS = "STAFF_SALARY_SUCCESS";
export const STAFF_SALARY_FAIL = "STAFF_SALARY_FAIL";
export const STAFF_SALARY_RESET = "STAFF_SALARY_RESET";

export const SUBMIT_PROPOSAL_REQUEST = "PROPOSAL_REGISTER_REQUEST";
export const SUBMIT_PROPOSAL_SUCCESS = "PROPOSAL_REGISTER_SUCCESS";
export const SUBMIT_PROPOSAL_FAIL = "PROPOSAL_REGISTER_FAIL";
export const SUBMIT_PROPOSAL_RESET = "PROPOSAL_REGISTER_RESET";

export const STAFF_DELETE_REQUEST = "STAFF_DELETE_REQUEST";
export const STAFF_DELETE_SUCCESS = "STAFF_DELETE_SUCCESS";
export const STAFF_DELETE_FAIL = "STAFF_DELETE_FAIL";
export const STAFF_DELETE_RESET = "STAFF_DELETE_RESET";

export const STAFF_LIST_REQUEST = "STAFF_LIST_REQUEST";
export const STAFF_LIST_SUCCESS = "STAFF_LIST_SUCCESS";
export const STAFF_LIST_FAIL = "STAFF_LIST_FAIL";
export const STAFF_LIST_RESET = "STAFF_LIST_RESET";
